//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoicenterRealtimeAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://loginapi.voicenter.co.il/monitorAPI/Login/User")]
        public string UserUrl {
            get {
                return ((string)(this["UserUrl"]));
            }
            set {
                this["UserUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://loginapi.voicenter.co.il/monitorAPI/Login/Account")]
        public string AccountUrl {
            get {
                return ((string)(this["AccountUrl"]));
            }
            set {
                this["AccountUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://loginapi.voicenter.co.il/monitorAPI/Login/Token")]
        public string TokenUrl {
            get {
                return ((string)(this["TokenUrl"]));
            }
            set {
                this["TokenUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://loginapi.voicenter.co.il/monitorAPI/RefreshIdentityToken")]
        public string RefreshTokenUrl {
            get {
                return ((string)(this["RefreshTokenUrl"]));
            }
            set {
                this["RefreshTokenUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int KeepAliveInterval {
            get {
                return ((int)(this["KeepAliveInterval"]));
            }
            set {
                this["KeepAliveInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ReconnectionAttempts {
            get {
                return ((int)(this["ReconnectionAttempts"]));
            }
            set {
                this["ReconnectionAttempts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Reconnection {
            get {
                return ((bool)(this["Reconnection"]));
            }
            set {
                this["Reconnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int ReconnectionDelay {
            get {
                return ((int)(this["ReconnectionDelay"]));
            }
            set {
                this["ReconnectionDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://monitor5.voicenter.co.il")]
        public string monitorURI {
            get {
                return ((string)(this["monitorURI"]));
            }
            set {
                this["monitorURI"] = value;
            }
        }
    }
}
